### ISSUE TITLE
Support formatting option: vertical align 

### ISSUE THREAD

**Issue by ngdangtu-vn** [beautifier/js-beautify#2275]
# Description

I prefer a neat list with proper align for CSS, Js/Ts and HTMl 

# Input
With this new feature, when I give like this input: 

```html
<input
    id="ok"
    name="ok"
    autocomplete="off"
/>
```

```css
:root {
   --round-small: 0.0625rem; // 1px
   --round-medium: 0.125rem; // 2px
   --round-pretty-big: 0.25rem; // 4px
}
```

# Expected Output
I'd like to see this output:

```html
<input
    id           ="ok"
    name         ="ok"
    autocomplete ="off"
/>
```

```css
:root {
   --round-small      : 0.0625rem; // 1px
   --round-medium     : 0.125rem; // 2px
   --round-pretty-big : 0.25rem; // 4px
}
```

For Js/Ts is when you group all declaration vars (no newline) or you have a list (array, map) in multiple lines.

## Environment
OS: Linux

Somehow on my pc the github didn't display monospace font properly so I didn't see a correct vertical align, hopefully you can see it on your side.
