### ISSUE TITLE
'Space Around Selector Separator" breaks valid double selectors in (S)CSS

### ISSUE THREAD

**Issue by TheDutchCoder** [beautifier/js-beautify#2295]
# Description
The current implementation of `space_around_selector_separator` does not account for the `~=` selectorThere are a few "multi "selectors in CSS, but only `~=` is unaccounted for.

Reference: `~=` , `|=`.  `^=`, `$=` , `*=` 

# Input
The code looked like this before beautification:
```css
[class~='thing'] {
  color: red;
}
```

# Expected Output
The code should have looked like this after beautification:
```css
[class ~= 'thing'] {
  color: red;
}
```

# Actual Output
The  code actually looked like this after beautification:
```css
[class ~ ='thing'] {
  color: red;
}
```

# Steps to Reproduce
Use the online beautifier playground with this setting:
```json
{
 "space_around_selector_separator": true
}
```

and the following CSS:
```css
[class~='fa-chevron'] {
    color: red;
}
```

## Environment
OS: MacOS 14.5

## Settings
```json
{
  "indent_size": "4",
  "indent_char": " ",
  "max_preserve_newlines": "5",
  "preserve_newlines": true,
  "keep_array_indentation": false,
  "break_chained_methods": false,
  "indent_scripts": "normal",
  "brace_style": "collapse",
  "space_before_conditional": true,
  "unescape_strings": false,
  "jslint_happy": false,
  "end_with_newline": false,
  "wrap_line_length": "0",
  "indent_inner_html": false,
  "comma_first": false,
  "e4x": false,
  "indent_empty_lines": false,
  "space_around_selector_separator": true
}
```
